### ISSUE TITLE
Cant build as its missing Jither.Common

### ISSUE THREAD

**Issue by bgbennyboy** [Jither/iMUSE-Sequencer#1]
Jither.Common\Jither.Common.csproj : error  : The project file cannot be found.

This is an outrage, I want my money back! (Please can we have the common library too?)

**Comment by Jither** [comment]
It's in no way ready, bg :wink: - it barely even plays anything yet, since I started over on the basic MIDI stuff to make the sequencing part as dynamic as needed. I'll add the common library when it's a bit further. Maybe over the weekend.

**Comment by Jither** [comment]
Update: It will be there... eventually. (Removed the jokey "enhancement" tag)

**Comment by Jither** [comment]
Only a bit over two years later, and Jither.Common repository is now public. 😂
